In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\ADM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ADM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ADM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\ADM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\ADM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\ADM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: C:\Users\ADM\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

### Series Pandas Python

In [5]:
pandas_series = pd.Series([1, 2, 3, 4, 5])
pandas_series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
pandas_series[1]

np.int64(2)

In [15]:
pandas_series.values

array([1, 2, 3, 4, 5])

In [16]:
pandas_series[3]

np.int64(4)

In [24]:
acidentes = pd.Series([15, 16, 34, 10, 14, 30, 22, 11, 14, 20, 23, 34], index=['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez'])
acidentes

jan    15
fev    16
mar    34
abr    10
mai    14
jun    30
jul    22
ago    11
set    14
out    20
nov    23
dez    34
dtype: int64

In [25]:
acidentes['abr']

np.int64(10)

In [29]:
acidentes[0:6]

jan    15
fev    16
mar    34
abr    10
mai    14
jun    30
dtype: int64

In [30]:
acidentes[0:6].values

array([15, 16, 34, 10, 14, 30])

In [31]:
sem1 = acidentes[0:6].values
list(map(lambda x: x * 2, sem1))

[np.int64(30),
 np.int64(32),
 np.int64(68),
 np.int64(20),
 np.int64(28),
 np.int64(60)]

In [32]:
sem1

array([15, 16, 34, 10, 14, 30])

In [34]:
print(acidentes.mean())
print(acidentes.std())
print(acidentes.max())
print(acidentes.min())

20.25
8.518696016303306
34
10

In [36]:
acidentes.describe() #observar a questão dos quartis

count    12.000000
mean     20.250000
std       8.518696
min      10.000000
25%      14.000000
50%      18.000000
75%      24.750000
max      34.000000
dtype: float64

In [37]:
acidentes.sum()

np.int64(243)

In [42]:
list(filter(lambda x: x > 30, sem1))
list(map(lambda x: x > 30, sem1))

[np.False_, np.False_, np.True_, np.False_, np.False_, np.False_]

In [39]:
acidentes[6:].mean()

np.float64(20.666666666666668)

### Dataframes Pandas Python

In [45]:
dataframeDefinition = {
                        'Aluno': ['Carlos', 'Eduardo', 'Ingrid', 'Juan'],
                        'Créditos Cursados': [32, 96, 64, 96],
                        'Rendimento Acadêmico': [8.50, 9.22, 7.87, 8.95],
                        'Mês de nascimento': ['Novembro', 'Julho', 'Setembro', 'Janeiro'],
                        'Curso': ['Matemática', 'Computação', 'Estatística', 'Ciência de Dados']
}

df = pd.DataFrame(dataframeDefinition)
df

,Aluno,Créditos Cursados,Rendimento Acadêmico,Mês de nascimento,Curso
0,Carlos,32,8.50,Novembro,Matemática
1,Eduardo,96,9.22,Julho,Computação
2,Ingrid,64,7.87,Setembro,Estatística
3,Juan,96,8.95,Janeiro,Ciência de Dados

In [47]:
df.iloc[3]

Aluno                               Juan
Créditos Cursados                     96
Rendimento Acadêmico                8.95
Mês de nascimento                Janeiro
Curso                   Ciência de Dados
Name: 3, dtype: object

In [49]:
df['Rendimento Acadêmico']

0    8.50
1    9.22
2    7.87
3    8.95
Name: Rendimento Acadêmico, dtype: float64

In [52]:
df['Rendimento Acadêmico'].values.mean()

np.float64(8.635)

In [50]:
df['Rendimento Acadêmico'].mean()

np.float64(8.635)

In [53]:
df['Rendimento Acadêmico'].describe()

count    4.000000
mean     8.635000
std      0.590169
min      7.870000
25%      8.342500
50%      8.725000
75%      9.017500
max      9.220000
Name: Rendimento Acadêmico, dtype: float64

In [54]:
df.describe()

       Créditos Cursados  Rendimento Acadêmico
count           4.000000              4.000000
mean           72.000000              8.635000
std            30.637667              0.590169
min            32.000000              7.870000
25%            56.000000              8.342500
50%            80.000000              8.725000
75%            96.000000              9.017500
max            96.000000              9.220000

## Trabalhando com CSV

In [55]:
df = pd.read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv')

In [56]:
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
...,...,...,...,...,...
188,Venezuela,333,100,3,7.7
189,Vietnam,111,2,1,2.0
190,Yemen,6,0,0,0.1
191,Zambia,32,19,4,2.5
192,Zimbabwe,64,18,4,4.7

In [57]:
df.head(6)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
5,Antigua & Barbuda,102,128,45,4.9

In [59]:
df[df['country'] == 'Brazil']

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
23,Brazil,245,145,16,7.2

In [60]:
df[df['total_litres_of_pure_alcohol'] >= 12]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
3,Andorra,245,138,312,12.4
15,Belarus,142,373,42,14.4
98,Lithuania,343,244,56,12.9

In [64]:
df[df['total_litres_of_pure_alcohol'] == 0].head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
13,Bangladesh,0,0,0,0.0
46,North Korea,0,0,0,0.0
79,Iran,0,0,0,0.0
90,Kuwait,0,0,0,0.0

In [66]:
df.sort_values(by='wine_servings', ascending=False).head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
61,France,127,151,370,11.8
136,Portugal,194,67,339,11.0
3,Andorra,245,138,312,12.4
166,Switzerland,185,100,280,10.2
48,Denmark,224,81,278,10.4